FMPREL/Controllers/CartoesController.cs
using FMPREL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FMPREL.Controllers
{
    public class CartoesController : Controller
    {
        DbModel db = new DbModel();

        public ActionResult Index()
        {
            var jogadores = db.Jogador.Where(x => x.CartoesAmarelos.Any(y => !y.Cumpriu)).Select(x => new JogadorDto
            {
                Nome = x.Nome + " - (" + x.Time.Apelido + ")",
                Quantidade = x.CartoesAmarelos.Count(y => !y.Cumpriu),
                Amarelo = true
            });

            jogadores = jogadores.Union(db.Jogador.Where(x => x.CartoesVermelhos.Any(y => !y.Cumpriu)).Select(x => new JogadorDto
            {
                Nome = x.Nome + " - (" + x.Time.Apelido + ")",
                Quantidade = x.CartoesVermelhos.Count(y => !y.Cumpriu),
                Amarelo = false
            }));

            //new ControleDeAcessos().NovoAcesso(Paginas.Artilheiros);
            return View(jogadores.OrderByDescending(x => x.Quantidade));
        }
    }
}

FMPREL/Controllers/GruposController.cs
using FMPREL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FMPREL.Controllers
{
    public class GruposController : Controller
    {
        DbModel db = new DbModel();
        // GET: Grupos
        public ActionResult Index()
        {
            var times = db.Time.Select(x => new GrupoDto
            {
                Time = x.Apelido,
                Derrotas = x.Jogos.Where(y => y.IdPerdedor == x.Id).Count(),
                Vitorias = x.Jogos.Where(y => y.IdVencedor == x.Id).Count(),
                Empates = x.Jogos.Where(y => y.Empate).Count(),
                GF = x.Gols.Count(),
                GS = 0,
                Saldo = 0,
                CA = x.CartoesAmarelos.Count(),
                CV = x.CartoesVermelhos.Where(y => !y.Acumulado).Count(),
                Jogos = x.Jogos.Where(z => z.Encerrado).Count(),
                Pontos = x.Jogos.Where(z => z.IdVencedor == x.Id).Count() * 3 + x.Jogos.Where(z => z.Empate).Count(),
                Grupo = x.Grupo,
                Logo = x.Logo,
                IdTime = x.Id
            }).ToList();

            int gs;
            foreach (var item in times)
            {
                gs = db.Gol.Where(x => x.IdTime != item.IdTime).Count();
                item.Saldo = item.GF - gs;
                item.GS = gs;
            }
            times.Sort(new ClassificaoComparer());

            int i = 1;
            foreach (var item in times.Where(x => x.Grupo == "A"))
            {
                item.Posicao = i;
                i++;
            }
            i = 1;
            foreach (var item in times.Where(x => x.Grupo == "B"))
            {
                item.Posicao = i;
                i++;
            }
            new ControleDeAcessos().NovoAcesso(Paginas.Grupos);
            return View(times);
        }
    }

    internal class ClassificaoComparer : IComparer<GrupoDto>
    {
        public int Compare(GrupoDto x, GrupoDto y)
        {
            int comparacao = y.Pontos.CompareTo(x.Pontos);
            if (comparacao == 0)
                comparacao = y.Saldo.CompareTo(x.Saldo);
            if (comparacao == 0)
                comparacao = y.GF.CompareTo(x.GF);
            //if (comparacao == 0)
            //    comparacao = x.Saldo.CompareTo(y.Saldo);

            return comparacao;
        }
    }
}

FMPREL/Controllers/MelhoresController.cs
using FMPREL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FMPREL.Controllers
{
    public class MelhoresController : Controller
    {
        DbModel db = new DbModel();

        public ActionResult Index()
        {
            var jogadores = db.MelhorJogador.Where(x => !x.Goleiro).GroupBy(x => x.IdJogador).Select(x => new JogadorDto
            {
                Nome = x.FirstOrDefault().Jogador.Nome + " - (" + x.FirstOrDefault().Jogador.Time.Nome + ")",
                Quantidade = x.Count(),
                Goleiro = false
            });

            jogadores = jogadores.Union(db.MelhorJogador.Where(x => x.Goleiro).GroupBy(x => x.IdJogador).Select(x => new JogadorDto
            {
                Nome = x.FirstOrDefault().Jogador.Nome + " - (" + x.FirstOrDefault().Jogador.Time.Nome + ")",
                Quantidade = x.Count(),
                Goleiro = true
            }));

            new ControleDeAcessos().NovoAcesso(Paginas.Melhores);
            return View(jogadores.OrderByDescending(x => x.Quantidade));
        }
    }
}

FMPREL/Controllers/TimesController.cs
using FMPREL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FMPREL.Controllers
{
    public class TimesController : Controller
    {
        DbModel db = new DbModel();
        // GET: Times
        public ActionResult Index()
        {
            new ControleDeAcessos().NovoAcesso(Paginas.Times);
            return View(db.Time);
        }

        public ActionResult Time(int id)
        {
            new ControleDeAcessos().NovoAcesso(Paginas.Time);
            return View(db.Time.Find(id));
        }

        [HttpPost]
        public ActionResult Partidas(int id)
        {
            var time = new Time { Nome = "À definir", Logo = "" };
            var partidas = db.Time.Find(id).Jogos.Select(x => new DtoJogoRodada
            {
                DataEHora = x.Data,
                logoA = x.Times.DefaultIfEmpty(time).FirstOrDefault().Logo,
                logoB = x.Times.DefaultIfEmpty(time).LastOrDefault().Logo,
                data = x.Data.ToString("dd-MM-yy : HH:mm"),
                timeA = x.Times.DefaultIfEmpty(time).FirstOrDefault().Apelido,
                timeB = x.Times.DefaultIfEmpty(time).LastOrDefault().Apelido,
                placar = x.Gols.Where(y => y.IdTime == x.Times.FirstOrDefault().Id).Count() + " : " + x.Gols.Where(y => y.IdTime == x.Times.LastOrDefault().Id).Count()
            }).OrderBy(x => x.DataEHora).ToList();
            return PartialView(partidas);

        }
    }
}

FMPREL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Team HTML</title>
    <link rel="icon" href="../../images/favicon.ico" type="image/x-icon">

    @Styles.Render("~/css/library/bootstrap.css")
    @Styles.Render("~/dev-assets/preloader-default.css")
    @Styles.Render("~/dev-assets/demo-switcher.css")
</head>
<body>
    <div class="preloader-wrapper" id="preloader">
        <div class="motion-line dark-big"></div>
        <div class="motion-line yellow-big"></div>
        <div class="motion-line dark-small"></div>
        <div class="motion-line yellow-normal"></div>
        <div class="motion-line yellow-small1"></div>
        <div class="motion-line yellow-small2"></div>
    </div>

    <!--MAIN MENU WRAP BEGIN-->
    <div class="main-menu-wrap sticky-menu">
        <div class="container">
            <a class="custom-logo-link"><img src="~/images/soccer/logo.png" alt="logo" class="custom-logo"></a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#team-menu" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <nav class="navbar">
                <div class="collapse navbar-collapse" id="team-menu">
                  <ul class="main-menu nav">
                    <li>
                      <a href="@Url.Action("Index", "Home")"><span>Início</span></a>
                    </li>
                    <li>
                      <a href="#"><span>Classificação</span></a>
                      <ul>
                        <li><a href="@Url.Action("Index", "Grupos")"><span>Grupos</span></a></li>
                        <li><a href="@Url.Action("Index", "Eliminatorias")"><span>Eliminatórias</span></a></li>
                      </ul>
                    </li>
                    <li>
                      <a href="@Url.Action("Index", "Partidas")"><span>Partidas</span></a>
                    </li>
                    <li>
                      <a href="@Url.Action("Index", "Times")"><span>Times</span></a>
                    </li>
                    <li>
                      <a href="@Url.Action("Index", "Artilheiros")"><span>Artilheiros</span></a>
                    </li>
                    <li>
                      <a href="@Url.Action("Index", "Cartoes")"><span>Cartões</span></a>
                    </li>
                    <li>
                      <a href="@Url.Action("Index", "Melhores")"><span>Melhores</span></a>
                    </li>
                    @*<li>
                      <a href="#"><span>Configurações</span></a>
                      <ul>
                          <li><a href="#"><span>Jogo Realizado</span></a></li>
                        <li><a href="#"><span>Novo Jogo</span></a></li>
                        <li><a href="#"><span>Melhores</span></a></li>
                        <li><a href="#"><span>Cartões</span></a></li>
                      </ul>
                    </li>*@
                  </ul>
                </div>
            </nav>
        </div>
    </div>
    <!--MAIN MENU WRAP END-->

    @RenderBody()



    <!--FOOTER BEGIN-->
    <footer class="footer">
        <div class="wrapper-overfllow">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-12">
                        <div class="footer-left">
                            <div class="wrap" style="margin-top: -50px">
                                <img src="~/images/soccer/logo2_.png" alt="footer-logo">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-menu-wrap">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <a href="#top" class="foot-up"><span>Subir <i class="fa fa-caret-up" aria-hidden="true"></i></span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-xs-6">
                        <div class="copyrights">
                            <a>FMPREL</a>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="created">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--FOOTER END-->
    @Scripts.Render("~/js/library/jquery.js")
    @Scripts.Render("~/js/library/jquery-ui.js")
    @Scripts.Render("~/js/library/bootstrap.js")
    @Scripts.Render("~/js/library/jquery.sticky.js")
    @Scripts.Render("~/js/library/jquery.jcarousel.js")
    @Scripts.Render("~/js/library/jcarousel.connected-carousels.js")
    @Scripts.Render("~/js/library/owl.carousel.js")
    @Scripts.Render("~/js/library/progressbar.js")
    @Scripts.Render("~/js/library/jquery.bracket.min.js")
    @Scripts.Render("~/js/library/chartist.js")
    @Scripts.Render("~/js/library/Chart.js")
    @Scripts.Render("~/js/library/fancySelect.js")
    @Scripts.Render("~/js/library/isotope.pkgd.js")
    @Scripts.Render("~/js/library/imagesloaded.pkgd.js")
    @Scripts.Render("~/js/jquery.team-coundown.js")
    @Scripts.Render("~/js/matches-slider.js")
    @Scripts.Render("~/js/header.js")
    @Scripts.Render("~/js/matches_broadcast_listing.js")
    @Scripts.Render("~/js/news-line.js")
    @Scripts.Render("~/js/match_galery.js")
    @Scripts.Render("~/js/main-club-gallery.js")
    @Scripts.Render("~/js/product-slider.js")
    @Scripts.Render("~/js/circle-bar.js")
    @Scripts.Render("~/js/standings.js")
    @Scripts.Render("~/js/shop-price-filter.js")
    @Scripts.Render("~/js/timeseries.js")
    @Scripts.Render("~/js/radar.js")
    @Scripts.Render("~/js/slider.js")
    @Scripts.Render("~/js/preloader.js")
    @Scripts.Render("~/js/diagram.js")
    @Scripts.Render("~/js/bi-polar-diagram.js")
    @Scripts.Render("~/js/label-placement-diagram.js")
    @Scripts.Render("~/js/donut-chart.js")
    @Scripts.Render("~/js/animate-donut.js")
    @Scripts.Render("~/js/advanced-smil.js")
    @Scripts.Render("~/js/svg-path.js")
    @Scripts.Render("~/js/pick-circle.js")
    @Scripts.Render("~/js/horizontal-bar.js")
    @Scripts.Render("~/js/gauge-chart.js")
    @Scripts.Render("~/js/stacked-bar.js")
    @Scripts.Render("~/js/library/chartist-plugin-legend.js")
    @Scripts.Render("~/js/library/chartist-plugin-threshold.js")
    @Scripts.Render("~/js/library/chartist-plugin-pointlabels.js")
    @Scripts.Render("~/js/treshold.js")
    @Scripts.Render("~/js/visible.js")
    @Scripts.Render("~/js/anchor.js")
    @Scripts.Render("~/js/landing_carousel.js")
    @Scripts.Render("~/js/landing_sport_standings.js")
    @Scripts.Render("~/js/twitterslider.js")
    @Scripts.Render("~/js/champions.js")
    @Scripts.Render("~/js/landing_mainnews_slider.js")
    @Scripts.Render("~/js/carousel.js")
    @Scripts.Render("~/js/video_slider.js")
    @Scripts.Render("~/js/footer_slides.js")
    @Scripts.Render("~/js/player_test.js")
    @Scripts.Render("~/js/main.js")

    @Scripts.Render("~/dev-assets/demo-switcher.js")

    @RenderSection("scripts", required: false)

</body>

</html>